# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 23:50
from __future__ import unicode_literals

from django.db import migrations


def forwards(app, schema_editor):
    old_brand_model = app.get_model('parts', 'BikeBrand')
    new_brand_model = app.get_model('brands', 'BikeBrand')

    for brand in old_brand_model.objects.all():
        new_brand = new_brand_model(
            id=brand.id,
            name=brand.name
        )
        new_brand.save()


def backwards(app, schema_editor):
    new_brand_model = app.get_model('brands', 'BikeBrand')
    new_brand_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
