# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20160625_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeBrand',
        ),
    ]
